### ISSUE TITLE
错误：创建词语 管理员修改无效

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-web#103]
**描述错误**
清晰明了地描述错误是什么？
我在管理员审核界面将其修改为：莆仙民俗，每月初二、十六祭拜财神、土地公，也招呼伙计吃一顿。每年二月初二称为“头牙”，十二月十六称为“尾牙”。正月时不“做牙”。
但是实际上显示的不是
我怀疑可能是后端也有写入操作？

**屏幕截图**
如果可以的话，尽量提供一些截图来描述你的问题。
![image](https://user-images.githubusercontent.com/20886330/213855026-c0e64e4d-ac22-48a3-83df-601cbf2c475a.png)

**Comment by 123daxian** [comment]
复现错误时发现，更明确的bug是：创建词语-审核员修改-通过-会出现两个词条：一个是修改前的，一个是修改后的

**Comment by Norton-Lin** [comment]
后端逻辑已修复，目前可保证数据库无冗余词条信息

**Comment by FrogDar** [comment]
按现在的情况来看很有可能是前端的问题？  后端已经部署到测试服务器

**Comment by 123daxian** [comment]
emm我大概捋了捋思路
1、用户在提交申请的时候，触发WD0401申请更新的接口，此时由于word为0，为创建新词条（然后这个时候生成一个申请A）
2、管理员审核，通过（申请A通过，A词条产生）（也就是管理员只是在审核界面做是否通过该申请的操作而已，并没有对该申请里词条的字段有修改的操作）
3、在管理员审核界面，之前不是管理员的修改没有保存嘛，所以当时我就调用了WD0402管理员上传新词条和WD0403管理员更改词条这两个接口。这个时候由于该词条还没有被创建（还没有通过审核），所以只能进入WD0402的接口，所以就生成了词条B了。
4、所以...解决方案应该是，不调用WD0402和WD0403接口，但是WD0404审核申请，除了通过用户的词条，还应该再有一个覆盖原申请词条字段信息的操作？或者是新增一个 更新申请的字段？

**Comment by FrogDar** [comment]
所以之前重构的时候应该出现了一些问题吧？
因为我最早的逻辑是，如果是创建新词语的话，点击确认修改按钮应该先触发审核通过（产生新词条）再修改词语
这样不就可以了么？
