### ISSUE TITLE
错误：未审核筛选下  审核操作后出现 已审核语音

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-web#109]
**描述错误**
清晰明了地描述错误是什么？
未审核筛选下  审核操作后出现 已审核语音

**复现错误**
复现错误的步骤:
1. 筛选未审核词语
2. 点击审核
3. 审核结束后出现大量已审核词语

**预期行为**
清晰明了地描述理论上应该有什么反应？
列表保持未审核状态，或者只有刚才那个是审核通过

**屏幕截图**
如果可以的话，尽量提供一些截图来描述你的问题。
![image](https://user-images.githubusercontent.com/20886330/217759219-42811854-fbf3-4330-80c6-0a9d66a44ac7.png)

**Comment by FrogDar** [comment]
![image](https://user-images.githubusercontent.com/20886330/217760276-b0e165ed-8980-4d6b-8ea3-09e5ec2e4421.png)

未审核筛选 点击下一页之后 有点问题、

**Comment by 123daxian** [comment]
学长觉得“已审核”这一列重要吗，在“已审核”筛选情况去掉的情况下，我可以实现列表在操作后保持原来的筛选状态，所以就有些想去掉）

**Comment by FrogDar** [comment]
为啥未审核可以已审核不行？

**Comment by 123daxian** [comment]
emm跟我解决的逻辑有关系吧 我是想获取某个筛选情况下 granted visibility的取值 然后在审核操作后传这两个参数给getcurrentpage。未审核、已通过、未通过下所有语音granted visibility的情况是一样的，但是”已审核”下有两种情况 visibility可能为true or false

**Comment by FrogDar** [comment]
> granted visibility
已审核为啥不是只有 granted = true 一个条件呢？

**Comment by FrogDar** [comment]
> > granted visibility
> > 已审核为啥不是只有 granted = true 一个条件呢？

那未审核难道不是 granted = false ？ 
还是说 granted 只能查找某个具体的人？

**Comment by FrogDar** [comment]
> > > granted visibility
> > > 已审核为啥不是只有 granted = true 一个条件呢？
> 
> 那未审核难道不是 granted = false ？ 还是说 granted 只能查找某个具体的人？

如果是后者的话，那暂时先去掉这个已审核，然后去后端的仓库提issue 后续再加）
