### ISSUE TITLE
在亲戚计算器的按钮周围增加空白

### ISSUE THREAD

**Issue by charlie0129** [e-dialect/hinghwa-dict-web#11]
https://hinghwa.cn/tools/Relative

可以看到亲戚计算器的按钮是 **紧贴** 的，这样的 UI 看起来会比较奇怪

<img width="786" alt="image" src="https://user-images.githubusercontent.com/55270174/177307720-a6964024-09c9-418c-ba31-083c75a3a13e.png">

我们需要在周围增加空白，例如这样：

> 当然，样例图中 “己身” 并没有跟下面的按钮对齐，最终这是需要对齐的

<img width="898" alt="image" src="https://user-images.githubusercontent.com/55270174/177308637-41d4979a-9fc7-4b28-ae30-782d8c156c28.png">

如果你觉得一整排按钮不方便，能实现更好的布局的话那更好

**Comment by FrogDar** [comment]
@123daxian  Any progress on this issue?
