### ISSUE TITLE
反馈： 词单时间 24小时制

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-web#131]
![image](https://github.com/e-dialect/hinghwa-dict-web/assets/20886330/0cfce384-f9a7-4de2-807d-2c0f60cb2f10)

**Comment by Shxuuer** [comment]
时间格式跟浏览器所在时区有关，需不需要改

**Comment by FrogDar** [comment]
> 时间格式跟浏览器所在时区有关，需不需要改

这个是表达啥？

**Comment by Shxuuer** [comment]
时间格式化直接调用的Date类的toLocaleDateString方法，时间格式跟浏览器所在的时区有关

**Comment by FrogDar** [comment]
> 时间格式化直接调用的Date类的toLocaleDateString方法，时间格式跟浏览器所在的时区有关

![image](https://github.com/e-dialect/hinghwa-dict-web/assets/20886330/652ce074-97ef-4945-8047-f55b5b9c4531)

哦好吧，没理解你的意思）
确实在一个普通的大陆浏览器他就是没有问题的.jpg
