### ISSUE TITLE
没有登录不应该能评论

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-web#18]
![image](https://user-images.githubusercontent.com/20886330/180439371-2ec88232-61e3-4ea0-b997-3792945f7768.png)

**Comment by 123daxian** [comment]
发现可能不是 没有登录不能评论的问题？三天前我从小程序上 登录账号 评论了一篇文章，刚刚我在web上看我的评论也没有显示账号名字，而点击该头像进去确实是我的账号
<img width="613" alt="3" src="https://user-images.githubusercontent.com/106299221/183257822-eb4b57ac-5a21-4b6f-9dfb-ac234a1feb52.png">

**Comment by FrogDar** [comment]
> 发现可能不是 没有登录不能评论的问题？三天前我从小程序上 登录账号 评论了一篇文章，刚刚我在web上看我的评论也没有显示账号名字，而点击该头像进去确实是我的账号 <img alt="3" width="613" src="https://user-images.githubusercontent.com/106299221/183257822-eb4b57ac-5a21-4b6f-9dfb-ac234a1feb52.png">

你这个评论的是哪一个?你说的可能是另外一个bug了
但是此处的bug仍然存在 就是单纯字面意思…… 你随便看一篇文章就知道了

**Comment by FrogDar** [comment]
![image](https://user-images.githubusercontent.com/20886330/183258256-b0349234-d849-4805-a056-9218d15a82bf.png)

哪怕他其实会显示无权进行操作，但是前端不应该出现这些框框

**Comment by 123daxian** [comment]
我的这个评论在文章177，刚刚我也点进文章99了，这些评论都是有账号的人呀，点进他们的头像是有账号的，所以他们应该还是登陆了才评论的吧
我刚刚没有登录，确实没有评论成功

**Comment by FrogDar** [comment]
1. 现在没有登录
![image](https://user-images.githubusercontent.com/20886330/183258438-b490cf0b-180a-4819-b0d6-fd15cf8f8d5f.png)
2. 出现了评论框（不应该让他出现）
![image](https://user-images.githubusercontent.com/20886330/183258471-4eb764b5-24f3-49fc-992d-8e7a4fa9cfbd.png)
3. 出现了回复评论（不应该让他出现）
![image](https://user-images.githubusercontent.com/20886330/183258485-6b135414-fb4f-48e1-88c0-f6f5c15459a2.png)

**Comment by 123daxian** [comment]
哦哦哦sry明白了orz

**Comment by 123daxian** [comment]
emm还没弄出来 明天我再试试
