### ISSUE TITLE
反馈：修改语音不符合用户使用习惯

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-web#53]
遇到一个拼音，管理员修改其内容后可能会习惯点击“重新审核” 而不是保存修改

![P1YZ5 @6(7EI$8VQQNP}HZ8](https://user-images.githubusercontent.com/20886330/209103061-7fe07b34-216d-4738-a108-3b4f7dfe74bb.png)

可能需要想办法重新布局或者是更改文字提示

**Comment by 123daxian** [comment]
点击“重新审核”添加一个文字提示？like“您做的修改将无法保留，确定重新审核该词条吗？”
