### ISSUE TITLE
错误：首页说明字体过小

### ISSUE THREAD

**Issue by charlie0129** [e-dialect/hinghwa-dict-web#90]
**描述错误**

首页红圈部分字体大小不合适，与其他文字相比明显过小

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/55270174/212537829-e0cce13e-941f-48d0-a626-fdcb1b921e8b.png">

**预期行为**

字体大小差距不宜过大，用灰色表示说明文字

**屏幕截图**
如果可以的话，尽量提供一些截图来描述你的问题。

**电脑 (请填写下列信息):**
 - Safari 15.6.1, macOS 10.15.7, `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15`
 - Edge 108.0.1462.54, macOS 10.15.7, `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
 - 屏幕分辨率 5120x2880 ，缩放 200%

**附加内容**
任何其他有关错误的内容

**Comment by FrogDar** [comment]
这个问题和浏览器其实是相关，我觉得是写死的 8px 不太合适？ 或许需要调整一下

以及 这个字的颜色可以考虑改成灰色
